### ISSUE TITLE
Request for Debian 12 "bookworm" image

### ISSUE THREAD

**Issue by ganto** [geerlingguy/docker-debian11-ansible#6]
Debian 12 aka "bookworm" was [just released](https://www.debian.org/News/2023/20230610). Would it be possible to have an Ansible image for it?

**Comment by geerlingguy** [comment]
Working on it ;)

**Comment by geerlingguy** [comment]
GitHub: https://github.com/geerlingguy/docker-debian12-ansible

Docker Hub: https://hub.docker.com/r/geerlingguy/docker-debian12-ansible
